---
mgmt_gateway: 172.16.1.1

# Spine switch group
spine:
  defaults:
    platform: ceos
    loopback_ipv4_pool: 10.255.0.0/27
    loopback_ipv6_pool: fc00:dead:beef:128::/64
    bgp_as: 65100

  nodes:
    - name: dc1-spine1
      id: 1
      mgmt_ip: 172.16.1.11/24

    - name: dc1-spine2
      id: 2
      mgmt_ip: 172.16.1.12/24

# L3 Leaf switch group
l3leaf:
  defaults:
    platform: ceos
    loopback_ipv4_pool: 10.255.0.0/27
    loopback_ipv6_pool: fc00:dead:beef:128::/64
    loopback_ipv4_offset: 2
    loopback_ipv6_offset: 2
    vtep_loopback_ipv4_pool: 10.255.1.0/27
    uplink_switches: ['dc1-spine1', 'dc1-spine2']
    uplink_ipv4_pool: 10.255.255.0/26
    # Definition of pool of IPs to be used for MLAG peer-link connectivity
    mlag_peer_ipv4_pool: 10.255.1.64/27
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv4_pool: 10.255.1.96/27
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

  node_groups:
    - group: DC1_L3_LEAF1
      bgp_as: 65101
      filter:
        tags: [ "DC1-RACK1" ]
      nodes:
        - name: dc1-leaf1a
          id: 1
          mgmt_ip: 172.16.1.101/24
          uplink_switch_interfaces:
            - Ethernet1
            - Ethernet1
        - name: dc1-leaf1b
          id: 2
          mgmt_ip: 172.16.1.102/24
          uplink_switch_interfaces:
            - Ethernet2
            - Ethernet2

    - group: DC1_L3_LEAF2
      bgp_as: 65102
      filter:
        tags: [ "DC1-RACK2" ]
      evpn_gateway:
        # Specific BGP EVPN Gateway functionality for route types 2 (MAC-IP), 3 (IMET) and 5 (IP-PREFIX) can be enabled separately as needed.
        evpn_l2:
          enabled: true
        evpn_l3:
          enabled: true
          inter_domain: true
      nodes:
        - name: dc1-leaf2a
          id: 3
          mgmt_ip: 172.16.1.103/24
          uplink_switch_interfaces:
            - Ethernet3
            - Ethernet3
          evpn_gateway:
            # Define remote peers of the EVPN VXLAN Gateway.
            # If the hostname can be found in the inventory, ip_address and BGP ASN will be automatically populated.
            # Manual override takes precedence. If the peer's hostname can not be found in the inventory, ip_address and bgp_as must be defined.
            remote_peers:
              - hostname: dc2-leaf2a
        - name: dc1-leaf2b
          id: 4
          mgmt_ip: 172.16.1.104/24
          uplink_switch_interfaces:
            - Ethernet4
            - Ethernet4
          evpn_gateway:
            # Define remote peers of the EVPN VXLAN Gateway.
            # If the hostname can be found in the inventory, ip_address and BGP ASN will be automatically populated.
            # Manual override takes precedence. If the peer's hostname can not be found in the inventory, ip_address and bgp_as must be defined.
            remote_peers:
              - hostname: dc2-leaf2b

host:
  defaults:
    platform: ceos
    loopback_ipv4_pool: 10.255.0.0/27
    loopback_ipv4_offset: 6
    bgp_as: 65000
    spanning_tree_mode: mstp
  node_groups:
    - group: DC1-HOSTS-RACK1
      uplink_switches: ['dc1-leaf1a', 'dc1-leaf1b']
      nodes:
        - name: dc1-host1a
          id: 1
          mgmt_ip: 172.16.1.151/24
          uplink_switch_interfaces:
            - Ethernet10
            - Ethernet10
        - name: dc1-host1b
          id: 2
          mgmt_ip: 172.16.1.152/24
          uplink_switch_interfaces:
            - Ethernet11
            - Ethernet11

    - group: DC1-HOSTS-RACK2
      uplink_switches: ['dc1-leaf2a', 'dc1-leaf2b']
      nodes:
        - name: dc1-host2a
          id: 3
          mgmt_ip: 172.16.1.153/24
          uplink_switch_interfaces:
            - Ethernet10
            - Ethernet10
        - name: dc1-host2b
          id: 4
          mgmt_ip: 172.16.1.154/24
          uplink_switch_interfaces:
            - Ethernet11
            - Ethernet11